staticSites:
  - name: lisa-gaming
    branch: render-deploy
    buildCommand: 'echo "Using prebuilt dist from GitHub Actions"'
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html